use_frameworks!

platform :ios, '8.0'

target 'XAGuidePage_Example' do
  pod 'XAGuidePage', :path => '../'

  target 'XAGuidePage_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
